name: AdminUtils
version: 1.0
main: com.themissingcrowbar.adminUtils.Main

commands:
  getWarnings:
    usage: /<command> Player [limit] [asc-dsc]
    description: Get warnings of a player
    permission: adminutils.warnings.get

  warn:
    usage: /<command> Player {warnTypeName|warnTypeId} [offences] [reason]
    description: Warn a player, use getWarnTypes to get a list of warn types
    permission: adminutils.warnings.warn

  getWarnTypes:
    usage: /<command> [warnTypeName|warnTypeId]
    description: Get warnTypes, supply id or typeName to get description of that Type
    permission: adminutils.warnings.getWarnTypes

  editWarn:
    usage: /<command> warnId field newValue
    description: Edits a warning
    permission: adminutils.warnings.edit

  deleteWarn:
    usage: /<command> warnId
    description: Delete a warning from the database
    permission: adminutils.warnings.delete

